require: rubocop-rspec

Metrics/LineLength:
  Max: 120
  Exclude:
    - 'spec/**/*'

Documentation:
  Enabled: false

NamedSubject:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

Metrics/BlockLength:
  ExcludedMethods:
  Exclude:


Metrics/MethodLength:
  Exclude:


AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'

RSpec/MessageChain:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
