default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL', 5) %>
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  port: 5432
  username: <%= ENV.fetch('DB_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', 'postgres') %>
test:
  <<: *default
  database: bookstore_test
development:
  <<: *default
  database: bookstore_development
production:
  <<: *default
  database: bookstore_production
staging:
  <<: *default
  database: bookstore_staging
