default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: <%= Rails.application.credentials[Rails.env.to_sym][:database][:user_name] %>
  password: <%= Rails.application.credentials[Rails.env.to_sym][:database][:password] %>

development:
  <<: *default
  database: bookstore_development

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production
