default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: localhost
  database: bookstore_development
  username: ruby_psql
  password: <%= Rails.application.credentials.DEVELOPMENT_DATABASE_PASSWORD %>

test:
  <<: *default
  database: bookstore_test

production:
  <<: *default
  database: bookstore_production
